### ISSUE TITLE
Sales channel added and added again

### ISSUE THREAD

**Issue by mbretter** [shopware/deployment-helper#32]
Hi,

I am using the docker setup from shopwareLabs.

The deployment is working so far, but I if I am changing the sales channel/domains/language in the admin area, the sales channel gets created again, after invoking the deployment-helper.

If I am leaving the channel untouched, everything is working.

It seems, that the check, if the sales channel is already present, fails, IMHO it should check the URL only, as mentioned in #5.

cheers,

**Comment by shyim** [comment]
do you have `STOREFRONT_URL` specified?

**Comment by mbretter** [comment]
I have provided the SALES_CHANNEL_URL

and the helper definitely uses it:
```
php bin/console -n sales-channel:create:storefront --name=Storefront --url=https://shop-demo.xxx.yy/
```

**Comment by mbretter** [comment]
btw I am using the latest version of deployment-helper
```
shopware/deployment-helper         0.0.15
```

**Comment by shyim** [comment]
When you provide a `STOREFRONT_URL` it looks for an sales channel with that url, when not there it creates one. If you don't want this behaviour, remove that env variable

**Comment by mbretter** [comment]
Ok, I have found the issue, I have provided the url like this:
```
SALES_CHANNEL_URL=https://shop-demo.xxx.yy/
```
When saving the domain in the admin area, the trailing slash gets stripped automatically, for the deployment helper this means:
```
https://shop-demo.xxx.yy/ != https://shop-demo.xxx.yy
```
and it adds the sales channel again.

Btw, the STOREFRONT_URL environment variable does nothing, and it also not mentioned in the docs:
https://developer.shopware.com/docs/guides/hosting/installation-updates/deployments/deployment-helper.html#environment-variables

**Comment by shyim** [comment]
fixed with https://github.com/shopware/deployment-helper/commit/72e3d10f25d527de3db7dab102ba6bdc0b205cfa
